#pragma once

#include <iostream>
#include <cstdlib> 
#include <time.h> 
#include <cctype> 
#include <iomanip>
#include <string>
#include <random>
#include <algorithm>
#include <limits>
#include <numeric>
#include <vector>

using std::cout;
using std::all_of;
using std::cin;
using std::endl;
using std::left;
using std::right;
using std::setw;
using std::setprecision;
using std::string;
using std::isalpha;
using std::copy;
using std::sort;
using std::fixed;
using std::vector;
using std::random_device;
using std::mt19937;
using std::uniform_int_distribution;
using std::streamsize;
using std::numeric_limits;
